<?php

namespace Duo\ModelBundle\Repository;

/**
 * AtividadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtividadeRepository extends \Doctrine\ORM\EntityRepository
{

	public function findAll()
	{
	    $qb = $this->getEntityManager()
        ->createQueryBuilder()
        ->select('atv.id,atv.title,atv.description,atv.status_id,atv.startDate,atv.endDate,atv.situation')
        ->from('DuoModelBundle:Atividade','atv')
        ->orderBy('atv.id', 'desc'); 
	    return $qb->getQuery()->getResult();
	}

	public function findFilter($id=null,$status_id=null,$situation=null)
	{
	     $qb = $this->getEntityManager()
        ->createQueryBuilder()
        ->select('atv.id,atv.title,atv.description,atv.status_id,atv.startDate,atv.endDate,atv.situation')
        ->from('DuoModelBundle:Atividade','atv');
        if($id) $qb->andWhere('atv.id = '.$id);
        if($status_id) $qb->andWhere("atv.status_id = '".$status_id."'");
        if($situation) $qb->andWhere("atv.situation = ".$situation);
	    return $qb->getQuery()->getResult();
	}
}
