<?php

namespace Duo\ModelBundle\Repository;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll()
	{
	    $qb = $this->getEntityManager()
        ->createQueryBuilder()
        ->select('sta.status_id,sta.title')
        ->from('DuoModelBundle:Status','sta')
        ->orderBy('sta.status_id', 'desc'); 
	    return $qb->getQuery()->getResult();

	}
}
